### ISSUE TITLE
error checking │ signature: openpgp: key expired

### ISSUE THREAD

**Issue by marcispauls** [StatusCakeDev/terraform-provider-statuscake#150]
**Describe the bug**
When i try to use provider i got:

<img width="1543" alt="image" src="https://github.com/StatusCakeDev/terraform-provider-statuscake/assets/1035938/dde32761-9ecb-404a-8505-9dc7dfbc3543">

**Additional context**
- ubuntu 22.04 runner
- hashicorp/setup-terraform@v2

**Comment by lra** [comment]
Yes, same issue for us, works with 1.5.x, does not work with 1.6.0.
```
Initializing the backend...

Initializing provider plugins...
- Finding statuscakedev/statuscake versions matching "~> 2.0"...
- Installing statuscakedev/statuscake v2.2.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing statuscakedev/statuscake v2.2.0: error checking signature: openpgp: key expired
╵
```

**Comment by marcispauls** [comment]
yes, checked with 1.5.x works, but that not solution sadly

**Comment by nimboya** [comment]
I am experiencing the same issue. 
![image](https://github.com/StatusCakeDev/terraform-provider-statuscake/assets/4225466/c7b1480d-0fc7-4961-aa66-39ca9e66a4fe)

**Comment by sharondescalo** [comment]
same error in terraform version 1.5.X using Atlantis.

**Comment by nimboya** [comment]
@sharondescalo, It actually failed with I used 1.5.x too. But I fixed mine by downgrading to 1.4.4 that is what fixed it. 

If you are using the Github Action. You can specify the version like this 

```
steps:
- uses: hashicorp/setup-terraform@v2
  with:
    terraform_version: 1.4.4
    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
```

**Comment by tomasbasham** [comment]
That is interesting @sharondescalo. We're not able to reproduce this issue on the 1.5.x branch of the CLI - not using GitHub Actions.

```bash
$ ./terraform -version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/statuscakedev/statuscake v2.2.0

Your version of Terraform is out of date! The latest version
is 1.6.0. You can update by downloading from https://www.terraform.io/downloads.html

$ ./terraform init

Initializing the backend...

Initializing provider plugins...
- Finding statuscakedev/statuscake versions matching "~> 2.2.0"...
- Installing statuscakedev/statuscake v2.2.0...
- Installed statuscakedev/statuscake v2.2.0 (signed by a HashiCorp partner, key ID 4E916C2959C4EAA9)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

whereas using the latest version 1.6 we can reproduce the error

```bash
$ ./terraform -version
Terraform v1.6.0
on linux_amd64
+ provider registry.terraform.io/statuscakedev/statuscake v2.2.0

$ ./terraform init

Initializing the backend...

Initializing provider plugins...
- Finding statuscakedev/statuscake versions matching "~> 2.2.0"...
- Installing statuscakedev/statuscake v2.2.0...
╷
│ Error: Failed to install provider
│
│ Error while installing statuscakedev/statuscake v2.2.0: error checking signature: openpgp: key expired
╵
```

We've filed an issue with HasiCorp. Hopefully they have some more insight. As far as we are to believe the provider should not have broke between Terraform versions.

**Comment by sharondescalo** [comment]
i used `runatlantis/atlantis:v0.25.0 with deployment env `ATLANTIS_TERRAFORM_VERSION=1.46` and `ATLANTIS_TERRAFORM_VERSION=1.5.5` and i've got the same issue: 
![image](https://github.com/StatusCakeDev/terraform-provider-statuscake/assets/1915885/c24a59f5-c35c-48c5-b3c2-d13d2fa36093) in both cases.

**Comment by tomasbasham** [comment]
That looks to be a different issue. There is no version `2.20.0`. I think you may want `2.2.0`

**Comment by sharondescalo** [comment]
Sorry, it was typo. i used runatlantis/atlantis:v0.25.0 with deployment ENV A`TLANTIS_TERRAFORM_VERSION=1.4.6` and `ATLANTIS_TERRAFORM_VERSION=1.5.5`: 
![image](https://github.com/StatusCakeDev/terraform-provider-statuscake/assets/1915885/1ad3c739-1999-4feb-9658-da7d1560a020)

**Comment by sharondescalo** [comment]
issue fixed with terraform$ATLANTIS_TERRAFORM_VERSION init `-reconfigure`

**Comment by lra** [comment]
Just to be clear for newcomers, the issue is not fixed:
- It works with terraform < 1.6.0
- It does not work with terraform 1.6.0

**Comment by tomasbasham** [comment]
Version 2.2.1 of the provider has been released using a different signing key. From what I can tell Terraform 1.6 is working with this new version, as is the latest version in the 1.5.x branch.

I am to believe the original signing key used did not include an expiration so I've no clue as to why it would suddenly not work, and furthermore why only version 1.6 was effected.

**Comment by tomasbasham** [comment]
Thanks for the link btw @Zeneixe. It was really helpful

**Comment by lra** [comment]
Fix confirmed for us, thanks!
